### ISSUE TITLE
SSL cert for web app

### ISSUE THREAD

**Issue by ceteri** [Coleridge-Initiative/RCServer#8]
Need to coordinate with Clayton to get an SSL certificate issued for the `rc.coleridgeinitiative.org` domain.

Currently the server is running at <http://rc.coleridgeinitiative.org> where the stack is built from:

1. Cloudflare CDN and DNS (existing, only for HTTP, not HTTPS - Clayton has account access)
2. Nginx server (existing, Paco just needs to add SSL cert to get HTTPS)
3. Gunicorn WSGI-compliant bridge (running now)
4. Systemd process management (`systemctl` services)
5. Flask microframework running an app (which gets replicated)

What we need are the parts generated by Cloudflare for SSL:

- `.pem` file (the actual certificate)
- `.key` file (the associated private key)

... or other means to generate these from what Cloudflare will provide.

That will plug in here 
<https://github.com/Coleridge-Initiative/RCServer/blob/master/etc/richcontext.nginx>
on the GCP instance that's already running.

Also, here are some docs for general background, although we already have the config needed:

- <https://serverfault.com/questions/934132/how-to-configure-nginx-ssl-with-an-encrypted-key-in-pem-format>
- <http://nginx.org/en/docs/http/configuring_https_servers.html>

**Comment by ceteri** [comment]
@ernestogimeno @claytonrsh Here are instructions about:

- [Universal SSL](https://support.cloudflare.com/hc/en-us/articles/204151138) -- the free SSL cert

There will also be settings to manage and synchronize, such as HSTS and Authenticated Origin Pulls, which must be done *after* the SSL cert is already in place.  Perhaps then @claytonrsh and I could do a brief video call to walk through those settings.  They can be important for getting traffic into fed agencies, at least for passing the (free online) security audits -- and I'm set up for that.

**Comment by ceteri** [comment]
@claytonrsh @ernestogimeno we may be required to purchase a Dedicated SSL cert, since the `rc` subdomain is at second-level (not a `www` cname): 
<https://support.cloudflare.com/hc/en-us/articles/228009108>

> Universal SSL certificates only support SSL for the root or first-level subdomains such as example.com and www.example.com. To enable SSL support on second, third, and fourth level subdomains such as dev.www.example.com or app3.dev.www.example.com, you can:
> * Upgrade to a Business or Enterprise plan to upload a Custom SSL certificate.
>* Purchase a Dedicated SSL certificate with Custom Hostnames.

**Comment by ceteri** [comment]
the Dedicated SSL certs cost $5/month for upto 50 subdomains

- login
- select Cloudflare account for `coleridgeinitiative.org`
- click the `SSL/TLS` horizontal menu button
- click the `Edge Certificates` option

**Comment by ernestogimeno** [comment]
I think that rc.coleridgeinitiative.org is a first-level subdomain, where a second-level subdomain would be something.rc.coleridgeinitiative.org. At least according to what it says here: https://www.digicert.com/faq-general.htm

**Comment by ceteri** [comment]
If that works well, great.  In that case, we can try first with the default PEM + KEY files from `coleridgeinitiative.org` which @claytonrsh should be able to access and download?

**Comment by ceteri** [comment]
Used the EFF `Certbot` to generate a new SSL cert instead, which is passing the tests at https://www.ssllabs.com/ssltest/analyze.html?d=rc.coleridgeinitiative.org
